Get-AppxPackage *3dbuilder* | Remove-AppxPackage
Get-AppxPackage *alarms* | Remove-AppxPackage
Get-AppxPackage *calculator2* | Remove-AppxPackage
Get-AppxPackage *communications* | Remove-AppxPackage
Get-AppxPackage *camera* | Remove-AppxPackage
Get-AppxPackage *officehub* | Remove-AppxPackage
Get-AppxPackage *skypeapp* | Remove-AppxPackage
Get-AppxPackage *getstarted* | Remove-AppxPackage
Get-AppxPackage *zunemusic* | Remove-AppxPackage
Get-AppxPackage *maps* | Remove-AppxPackage
Get-AppxPackage *solitairecollection* | Remove-AppxPackage
Get-AppxPackage *bingfinance* | Remove-AppxPackage
Get-AppxPackage *zunevideo* | Remove-AppxPackage
Get-AppxPackage *bingnews* | Remove-AppxPackage
Get-AppxPackage *onenote* | Remove-AppxPackage
Get-AppxPackage *people* | Remove-AppxPackage
Get-AppxPackage *windowsphone* | Remove-AppxPackage
#Get-AppxPackage *photos* | Remove-AppxPackage
Get-AppxPackage *bingsports* | Remove-AppxPackage
Get-AppxPackage *soundrecorder* | Remove-AppxPackage
Get-AppxPackage *bingweather* | Remove-AppxPackage
Get-AppxPackage *xbox* | Remove-AppxPackage
Get-AppxPackage *freshpaint* | Remove-AppxPackage
Get-AppxPackage *wunderlist* | Remove-AppxPackage
Get-AppxPackage *eclipse* | Remove-AppxPackage
Get-AppxPackage *flipboard* | Remove-AppxPackage
Get-AppxPackage *duolingo* | Remove-AppxPackage
Get-AppxPackage *adobe* | Remove-AppxPackage
Get-AppxPackage *cellular* | Remove-AppxPackage
Get-AppxPackage *pics* | Remove-AppxPackage
Get-AppxPackage *translator* | Remove-AppxPackage
Get-AppxPackage *feedback* | Remove-AppxPackage